@echo off
set MYSQL=C:\laragon\bin\mysql\mysql-9.7.0-winx64\bin\mysql.exe
set DB=scholarship_system
set DIR=%~dp0database

echo Creating database...
%MYSQL% -u root -e "CREATE DATABASE IF NOT EXISTS scholarship_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

echo Running schema.sql...
%MYSQL% -u root %DB% < "%DIR%\schema.sql"
echo Running migration_add_otp_and_username.sql...
%MYSQL% -u root %DB% < "%DIR%\migration_add_otp_and_username.sql"
echo Running migration_add_token_expires.sql...
%MYSQL% -u root %DB% < "%DIR%\migration_add_token_expires.sql"
echo Running migration_telegram.sql...
%MYSQL% -u root %DB% < "%DIR%\migration_telegram.sql"
echo Running migration_scholarship_types.sql...
%MYSQL% -u root %DB% < "%DIR%\migration_scholarship_types.sql"
echo Running migration_bakong_khqr.sql...
%MYSQL% -u root %DB% < "%DIR%\migration_bakong_khqr.sql"
echo Running migration_enrollment_details.sql...
%MYSQL% -u root %DB% < "%DIR%\migration_enrollment_details.sql"
echo Running migration_enrollment_payment.sql...
%MYSQL% -u root %DB% < "%DIR%\migration_enrollment_payment.sql"
echo Running migration_enrollment_settings.sql...
%MYSQL% -u root %DB% < "%DIR%\migration_enrollment_settings.sql"
echo Running migration_major_tuition.sql...
%MYSQL% -u root %DB% < "%DIR%\migration_major_tuition.sql"
echo Running seed.sql...
%MYSQL% -u root %DB% < "%DIR%\seed.sql"

echo Done! All migrations completed.
pause
