-- Migration: Add enrollment detail fields for registration form
-- Adds personal info, parent info, address, payment details to enrollments

ALTER TABLE enrollments
  ADD COLUMN khmer_first_name VARCHAR(255) AFTER semester,
  ADD COLUMN khmer_last_name VARCHAR(255) AFTER khmer_first_name,
  ADD COLUMN english_first_name VARCHAR(255) AFTER khmer_last_name,
  ADD COLUMN english_last_name VARCHAR(255) AFTER english_first_name,
  ADD COLUMN gender ENUM('male','female') AFTER english_last_name,
  ADD COLUMN date_of_birth DATE AFTER gender,
  ADD COLUMN place_of_birth VARCHAR(255) AFTER date_of_birth,
  ADD COLUMN phone VARCHAR(20) AFTER place_of_birth,
  ADD COLUMN current_address TEXT AFTER phone,
  ADD COLUMN province VARCHAR(100) AFTER current_address,
  ADD COLUMN district VARCHAR(100) AFTER province,
  ADD COLUMN commune VARCHAR(100) AFTER district,
  ADD COLUMN parent_name VARCHAR(255) AFTER commune,
  ADD COLUMN parent_phone VARCHAR(20) AFTER parent_name,
  ADD COLUMN parent_relationship VARCHAR(50) AFTER parent_phone,
  ADD COLUMN previous_school VARCHAR(255) AFTER parent_relationship,
  ADD COLUMN previous_diploma VARCHAR(255) AFTER previous_school,
  ADD COLUMN diploma_year INT AFTER previous_diploma,
  ADD COLUMN major VARCHAR(255) AFTER diploma_year,
  ADD COLUMN major_choice VARCHAR(255) AFTER major,
  ADD COLUMN bank_name VARCHAR(100) AFTER major_choice,
  ADD COLUMN bank_account_number VARCHAR(100) AFTER bank_name,
  ADD COLUMN bank_account_name VARCHAR(255) AFTER bank_account_number,
  ADD COLUMN photo_path VARCHAR(500) AFTER bank_account_name,
  ADD COLUMN student_signature_date DATE AFTER photo_path,
  ADD COLUMN parent_signature_date DATE AFTER student_signature_date;
